import { Router, type IRouter } from "express";
import healthRouter from "./health";
import eventsRouter from "./events";
import functionsRouter from "./functions";
import accountsRouter from "./accounts";
import contactsRouter from "./contacts";
import leadsRouter from "./leads";
import tasksRouter from "./tasks";
import notesRouter from "./notes";
import appointmentsRouter from "./appointments";
import guestRoomBlocksRouter from "./guestRoomBlocks";
import locationsRouter from "./locations";
import reportsRouter from "./reports";
import calendarRouter from "./calendar";
import dashboardRouter from "./dashboard";
import functionServicesRouter from "./functionServices";
import functionMenusRouter from "./functionMenus";
import serviceTypesRouter from "./serviceTypes";
import serviceItemsRouter from "./serviceItems";
import menuTemplatesRouter from "./menuTemplates";
import revenueCentersRouter from "./revenueCenters";
import paymentsRouter from "./payments";
import financialsRouter from "./financials";
import functionFinancialsRouter from "./functionFinancials";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/events", eventsRouter);
router.use("/events", financialsRouter);
router.use("/functions", functionsRouter);
router.use("/functions", functionServicesRouter);
router.use("/functions", functionFinancialsRouter);
router.use("/function-menus", functionMenusRouter);
router.use("/service-types", serviceTypesRouter);
router.use("/service-items", serviceItemsRouter);
router.use("/menu-templates", menuTemplatesRouter);
router.use(revenueCentersRouter);
router.use(paymentsRouter);
router.use("/accounts", accountsRouter);
router.use("/contacts", contactsRouter);
router.use("/leads", leadsRouter);
router.use("/tasks", tasksRouter);
router.use("/notes", notesRouter);
router.use("/appointments", appointmentsRouter);
router.use("/guest-room-blocks", guestRoomBlocksRouter);
router.use("/locations", locationsRouter);
router.use("/reports", reportsRouter);
router.use("/calendar", calendarRouter);
router.use("/dashboard", dashboardRouter);

export default router;
